language: android

android:
  components:
      # The BuildTools version used by your project
      - build-tools-21.1.2
      # Uncomment the lines below if you want to
      # use the latest revision of Android SDK Tools
      - platform-tools
      - tools
      # The SDK version used to compile your project
      - android-21


before_script:
    - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
    - echo yes | android update sdk --filter android-21 --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

script:
    - ./gradlew assembleDebug
